Small build-process improvements
ungoogled-software/ungoogled-chromium-portablelinux pull request #75
Opened 2020-11-07 22:45 UTC by iyesin

* Add a way for build-time modifications (like supplying extra gn-flags and pre/post build commands)

* Add a way to limit build-time CPU cores

* Get rid of external build-time script

* Make list of packages grep-able (one item per line)

2020-12-04 19:40 UTC, Eloston requested changes
Looks good in general, some more minor suggestions.

2020-12-04 19:40 UTC, Eloston commented on build.sh
> +[ -r "$_src_dir/../flags.local.gn" ] && cat "$_src_dir/../flags.local.gn" >> "$_src_dir/out/Default/args.gn"
It's cleaner to use `$_root_dir/flags.local.gn` and add a top-level `.gitignore` rule for `/flags.local.gn`. Sometimes I may symlink `$_src_dir`, so using `$_src_dir/../` can get confusing.

2020-12-04 19:40 UTC, Eloston commented on docker-build.sh
> +echo -e "${FLAGS}" > build/flags.local.gn
Do we need to create `flags.local.gn` here if we can just create the file ourselves separately?

2020-12-04 19:40 UTC, Eloston commented on docker-build.sh
> +docker run $NCPUS -ti -v `pwd`/build:/repo/build ug-chromium-builder-stage2:latest bash -c "$PRECMD && ./build.sh && ./package.sh && $POSTCMD"
Instead of adding PRECMD and POSTCMD here, why not just have a single `BUILDCMD` that by default consists of `./build.sh && package.sh`?

2023-12-10 23:41 UTC, clickot commented
the code base has changed too much to merge this PR

2023-12-10 23:41 UTC, closed without merging